version: "3.8"

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - API_KEY=${API_KEY}
      - BASE_URL=${BASE_URL}
    env_file:
      - .env
    volumes:
      - ./RAG_files:/app/RAG_files
    restart: unless-stopped
